#!/usr/bin/env python
# dwlw - A simple BeautifulSoup parser script for the website welklidwoord.nl, a website to find out which article (lidwoord) belongs to a noun (zelfstandig naamword) in the Dutch language. Inputs using dmenu and outputs using Notify Send.

from urllib.request import urlopen as uReq
from bs4 import BeautifulSoup as soup
import sys
import dmenu
import os
import notify2

znw_input = dmenu.show(['wlw'], prompt='De of het?')
def wlw(znw):
    znw_url = 'https://www.welklidwoord.nl/' + znw

    uClient = uReq(znw_url)
    page_html = uClient.read()
    uClient.close()
    page_soup = soup(page_html, "html.parser")
    ans = page_soup.find("h1").text

    return ans

wlw_ans = wlw(znw_input)

notify2.init('wlwans')
n = notify2.Notification(wlw_ans)
n.show()

